# Generated by Django 6.1.1 on 2026-10-02 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummonerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=10)),
                ('puuid', models.CharField(max_length=100, unique=True)),
                ('winrate', models.CharField(max_length=10)),
                ('kda', models.CharField(max_length=10)),
                ('cs_per_min', models.CharField(max_length=10)),
                ('ranked_solo', models.JSONField(blank=True, null=True)),
                ('ranked_flex', models.JSONField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=50)),
                ('win', models.BooleanField()),
                ('champion_name', models.CharField(max_length=50)),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('duration', models.CharField(max_length=15)),
                ('items', models.JSONField()),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.summonerprofile')),
            ],
        ),
    ]
