# Generated by Django 6.1.1 on 2026-10-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='participants_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='summonerprofile',
            name='profile_icon',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='summonerprofile',
            name='summoner_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
