# Generated by Django 6.1.1 on 2026-10-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_match_participants_data_summonerprofile_profile_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='runes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='spells',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
